<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <Version>0.6.0-alpha</Version>
      <Company>World-Direct eBusiness solutions GmbH</Company>
      <Copyright>2023</Copyright>
      <PackageLicenseFile>LICENSE</PackageLicenseFile>
      <PackageIcon>packageIcon.png</PackageIcon>
      <RepositoryUrl>https://github.com/world-direct/CoAP.NET</RepositoryUrl>
      <Description>
          Changelog:
      </Description>
  </PropertyGroup>

    <PropertyGroup>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\.nuget\icon.png" Link="icon.png">
            <PackagePath></PackagePath>
            <Pack>True</Pack>
        </None>
        <None Include="..\LICENSE" Link="LICENSE">
            <PackagePath></PackagePath>
            <Pack>True</Pack>
        </None>
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="..\packageIcon.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
  </ItemGroup>

</Project>
